#!/bin/bash
arr=($1)
filename=""
for e in ${arr[*]}
do
    if [[ "$filename" == "" ]];then
        filename="$e"    
    else
        filename="$filename""-$e"    
    fi
done
filename="$filename"".cc"
echo "$filename is created!"
touch "$filename"
